### PR TITLE
[WIP] Paper Trail and data history

### PR DESCRIPTION
**Pull request by piks3l**
**Update 14 Feb**: Simple views for the latest change work. It's _very_ basic, but that's something. I need to think a bit about the whole design of the show page for services. Meanwhile, I'll implement the diff for points in the same basic way. 

# What I did so far 
* Freezing PG gem version because the new release breaks
* Implementing Paper Trail gem and testing if it works on the models
* Adding the class to the show page of services
* Puts a display with tabs
* Show the latest change for a service with date (need UX work)

# Still to do
[X] Views for Services
[X] Views for Points
~[ ] What's up with the API and this~ (Michiel)

### CODE REVIEW

**Comment by michielbdejong** [comment]
> What's up with the API and this

I'll take care of that part! :)

**Comment by piks3l** [comment]
> I'll take care of that part! :)

Great thanks !

**Comment by piks3l** [comment]
So it isn't perfect (far from it and especially the UI) but it works. We can build from that now.

**Comment by michielbdejong** [comment]
Awesome! I will try to find time either during the weekend or next week to try out doing an export from this branch.

**Comment by piks3l** [comment]
Ok so we can merge ? It's a big one

**Pull request merged**
