### PR TITLE
[enh] Group cases by topic in the points form

### PR DESCRIPTION
**Pull request by Vinnl**
Improves #425, although it's still too hard to select a case for a point, in my opinion. That said, this PR makes it somewhat easier by grouping the cases by topic.

* [x] Are you working on the latest release?
* [x] Have you tested it locally?
* [x] Please mention if it is a fix (fix), enhancement (enh), modification (mod) or security (sec)
* [x] Please explain your change
* [x] If necessary, have you documented your feature on the wiki? 

Thanks !

### CODE REVIEW

**Comment by Vinnl** [comment]
@madoleary I think this code works. However, I removed one thing that you added earlier of which I wasn't sure whether it was necessary. Specifically: https://github.com/tosdr/phoenix/commit/96f26bcd931c0011ba6b97880ffd1689102c8dcb#diff-a8cbabe994854566e7feed9530cc4e6eR11

You wrapped the `f.select` in an `f.input`. What does that do? Did I break something by removing it?

**Comment by madoleary** [comment]
Yes. f.input needs to wrapped in f.select to get the functionality of
simple form. this is because the f.input tag itself is not actually simple
form functionality. it's a more fundamental rails functionality.

**Comment by Vinnl** [comment]
Right, so what functionality does simple form provide here? (Or perhaps the actual question I want to ask: should I add it back in, and how?)

**Comment by madoleary** [comment]
I'm having a hard time understanding why the default solution was to remove
it, if there wasn't an understanding of what it was doing there in the
first place. The selection of the case turns on this functionality: <%= f.
select :case_id, @cases.map { |c| [c.title, c.id, {'data-title' =>
c.title}, {'data-descrip' => c.description || "" }, {'data-rating' =>
c.classification}, {'topic' => c.topic.id} ] }, :include_blank => true %>.
This, and specifically the creation of multiple custom data fields, is not
available to simple form. So I had to use the rails form helpers. And then
to afford the field simple form functionality -- specifically, how simple
form formats the field and re-renders the field with errors -- I had to
wrap it in f.input, or else it was styled horribly, and, more importantly,
wouldn't re-render with the errors if case was left blank.

**Comment by madoleary** [comment]
I don't know how to explain how to add it back other than just telling you
to undo your changes...

**Comment by madoleary** [comment]
Ah, okay. I didn't see the full picture. Thanks for explaining. I need to
know what :grouped_select is to answer the question. The purpose of all
those custom data fields was to dynamically update title and description
depending on the case selected. It would be working correctly if those
fields are still dynamically updated. f.select needs to be used on the
inside if you're including all the custom data fields. And f.input on the
outside.

**Comment by Vinnl** [comment]
`:grouped_select` is [a simple_form setting](https://github.com/plataformatec/simple_form#collections) that allows you to create `<optgroup>`s, in this case, of topics with the cases linked to them.

The Title is still dynamically updated with the new code, as can be seen at https://edit.tosdr.org/points/new. There is no Description field, but that was already the case before I touched the code.

**Comment by madoleary** [comment]
I guess I meant "analysis." Different names for the same thing across
models, etc. It seems to be working alright. So I suppose we can just leave
it. Maybe there was another reason that I wrapped it in the f.input tag
that I can't remember right now. All I know is that it took a while to find
that solution and it had a specific purpose. Otherwise I'm not attached to
it. Just want to make sure the good functionality is in place, and it seems
to be.

**Comment by Vinnl** [comment]
Great, that's what I wanted to be sure of as well, so thanks for double-checking :)

**Pull request merged**
