### PR TITLE
[enh] Allow running the application locally with Docker Compose

### PR DESCRIPTION
**Pull request by Vinnl**
This allows developers to run Phoenix without having to set up Ruby and Postgres manually, possibly conflicting with other installations. Alternative instructions using Docker Compose have been added to `CONTRIBUTING.md`.

Note that I'm not 100% sure whether the way I add database credentials (i.e. through environment variables) won't clash with running the app without Docker, so please do give that a proper check.

### CODE REVIEW

**Comment by michielbdejong** [comment]
Awesome!! Will try it out :)

**Comment by michielbdejong** [comment]
I'm building it now on my laptop, will report if the instructions worked.

**Comment by michielbdejong** [comment]
Hm, I'm thinking this may be a timing issue, it's not giving the db server time to boot up?

```sh
$ docker-compose run web rails db:create db:migrate
Creating network "phoenix_default" with the default driver
Pulling db (postgres:latest)...
latest: Pulling from library/postgres
f2aa67a397c4: Pull complete
8218dd41bf94: Pull complete
e9b7fa2e6bd8: Pull complete
7288a45ee17f: Pull complete
0d0f8a67376c: Pull complete
670a6cc35896: Pull complete
813e44621756: Pull complete
7e84a0bda608: Pull complete
0ef886e21026: Pull complete
9b1a8cf1a4cb: Pull complete
2637aa79030a: Pull complete
3a11227b2bc0: Pull complete
952e84f32384: Pull complete
Digest: sha256:bcb7180d70bacbea299d51a3dbcb4d2804a0b529cf5e27f75bdf40ffef9272d9
Status: Downloaded newer image for postgres:latest
Creating phoenix_db_1 ... done
could not connect to server: Connection refused
	Is the server running on host "db" (172.18.0.2) and accepting
	TCP/IP connections on port 5432?
Couldn't create database for {"adapter"=>"postgresql", "encoding"=>"unicode", "pool"=>5, "host"=>"db", "username"=>"postgres", "password"=>nil, "database"=>"phoenix_development"}
rails aborted!
PG::ConnectionBad: could not connect to server: Connection refused
	Is the server running on host "db" (172.18.0.2) and accepting
	TCP/IP connections on port 5432?
/usr/local/bundle/gems/pg-0.21.0/lib/pg.rb:56:in `initialize'
/usr/local/bundle/gems/pg-0.21.0/lib/pg.rb:56:in `new'
/usr/local/bundle/gems/pg-0.21.0/lib/pg.rb:56:in `connect'
/usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/connection_adapters/postgresql_adapter.rb:695:in `connect'
/usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/connection_adapters/postgresql_adapter.rb:220:in `initialize'
/usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/connection_adapters/postgresql_adapter.rb:38:in `new'
/usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/connection_adapters/postgresql_

**Comment by michielbdejong** [comment]
When I run the `docker-compose run web rails db:create db:migrate` command a second time, it does work!

**Comment by Vinnl** [comment]
Huh, that's odd - I set the app to be dependent on the database in Docker Compose, so I was hoping for it to wait for that to start. Thanks for the workaround :)

**Pull request merged**
