### PR TITLE
WIP implementing cases

### PR DESCRIPTION
**Pull request by piks3l**
* [X] Are you working on the latest release?
* [X] Have you tested it locally?
* [X] Please explain your change

# Objective : 
Implementing "cases", categories of types of points (such as "cannot delete account") so they can have the same type of rating cross-services. Most of them are [here](https://github.com/tosdr/tosdr.org/tree/master/cases). Please comment if there is any issues.

# Update
So, big step here. Not only we are going to implement cases, but we are at the same time trying to review the submission process. So linking issues: #277, #249 (minor), #244, #241 and #240. The solution for steppers is easy: it's just some hidden css class so everytime the user click "ok", it will lead them to the next page. It's basically working like the tabs. Hopefully it will make the submission process more understandable for users. 

## Workflow
1. Is it an existing service ? 
  1.1 Yes : list
  1.2 No : create service
2. Display know categories (cases)
  2.1 Choose a case (if true already return a rating)
  2.2 Choose a topic
3. Give the analysis
  3.1 Title
  3.2 Content
  3.3 Rating (greyed out if its a case)
4. Review and submit
  4.1 Submit and done
  4.2 Submit and add another point

### CODE REVIEW

**Comment by piks3l** [comment]
# Issue / Need help

I'm having a bit of a problem, I'm writing it down here and hopefully tomorrow I'll solve or someone else would have. 

## Done
I've changed the submission layout the idea is now:
* choose a service
* does it have a case ? If yes, it is directly submitted and in the controller  the point is created with the case's parameters
### Issue
The simple form button is greyed and cannot submit. I believe it is because of the validations but bypassing the validation by removing them sounds like a bad idea. But I need to send a /post to the server otherwise the case won't be taken into account

Next:
* Need to find a better way to display the layout and the next button in case there is a submission of a point without a case. Also with different steps visually showed.

**Comment by madoleary** [comment]
The issue on my computer was that past a certain "step" (in relation to the JS), the submit buttons broke for non-case-related point-submission. Simple form is extremely sensitive to div design. There were stray divs at first, like two occurrences of "step-3" and dangling </div> tags. I don't think simple form liked "topic" and the rest of the point fields being in different "step" divs. I think there is also an issue with the "next" buttons, because if I accidentally pressed the "next" button after case more than once, the submit buttons broke again. I also don't understand why, in the points controller, we had @point.update_parameters under params[:only_create] and params[:create_add_another]? I've only ever seen update_parameters used for object edit/update, and not creation. Anyway, this needs more testing. Can work on it more tonight.

**Comment by piks3l** [comment]
Yeah, I'm trying two stuff here : 
1- Implementing cases within the submission process
2- Revamping the submission process.

Both of the part don't work, especially the 2. The submit button broke for some reasons, need investigating. Thanks for your input, I guess the error had something to do with this

**Comment by madoleary** [comment]
The submit buttons seem to work with my latest commit. I put all the form fields in the same "step" div. It's step 3. But the issue with the next button remains. I think an easy fix that makes sense would be to render that html empty after the button is pressed, since I don't think there would be further need for the case box if the case doesn't exist.

**Comment by piks3l** [comment]
Well, the point is kinda to try to ease the way people submit point with small step, I guess putting all in the same div (https://github.com/tosdr/phoenix/pull/263/commits/40e03c258c4839db3f58fbcecf20acfc1b7abc74) breaks this logic, right ? It's like going back in the previous situation.

My point would be to follow the workflow I explained in the first post here and have 4 steps.

**Comment by madoleary** [comment]
I got the submit buttons to work within the four-step specification. The problem was that the 'button' tags around 'next' were tricking simple form into making post requests, thus rendering the actual submit buttons broken. I just wrapped 'next' in spans that are styled to look like buttons. The problem now is that 'service' isn't saving to point on create.

**Comment by madoleary** [comment]
Point submission via cases is working now. It's also working without cases, but the UX problem is that right now the user needs to select the service twice. Service wasn't being passed to the second form, which is why point submission was failing beyond cases. I think some JavaScript/AJAX will solve this problem. Also the form needs serious styling. AJAX and I are not exactly best friends, but I'm going to keep experimenting. Cases are so cool! Stoked about this feature. I commented out all the validations just for testing purposes (and forgot to un-comment), and regarding the migration files, I was just stripping the model Case down to it's most basic form to get it to work step by step.

**Comment by madoleary** [comment]
The standard submission forms are re-rendering with errors now. Cases work a bit differently, and the form fields for cases weren't rendering the errors if, for example, the fields for "status" or "source" were left blank. So I made a custom flash error in the event that a user tries to submit a point via cases with empty form fields. It's all working pretty well now.

**Comment by piks3l** [comment]
So cool ! Thanks ! Tell us when you feel it's ready to be tested and merged :)

**Comment by michielbdejong** [comment]
> in the controller the point is created with the case's parameters

Is that what's currently implemented in this branch? We can merge it that way, but for a follow-up ticket, I think it's better to always have the rating data in the cases table. if a point has no case, then we create a one-off case in the cases table, and give the point a `case_id` that points to it. Then, you can even reuse that case later for another service.

**Comment by piks3l** [comment]
> We can merge it that way, but for a follow-up ticket,

Please, could you try it out on localhost to see if everything is working before merging ? 

> I think it's better to always have the rating data in the cases table. if a point has no case, then we create a one-off case in the cases table, and give the point a case_id that points to it. Then, you can even reuse that case later for another service.

As for what I understood, each point has a rating, a topic and a service but not necessarily a case.  Sometimes some points are recurrent throughout various services, we have cases that allow to create quickly a point for new service with a pre-set rating and topic. 

If I understand your system, each point is also a case, right? It could be interesting as we won't have to create cases manually but on the other side, it will require for us to improve the way users select a case form the interface as for now it isn't very simple.

**Comment by michielbdejong** [comment]
yes, let's keep the current design for now, i'm testing it locally. I have imported a dump of live data, and on http://localhost:3000/points/new I tried to set Service:'BearShare', Case:'age limit', Status:'pending', Source:'asdf', 'Submit Point'. I see the following validation errors in the `rails server` log:
```sh
Started POST "/points" for 127.0.0.1 at 2018-05-22 11:39:04 +0200
Processing by PointsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"YLbCkxrQqM/5ohUq7G0IwJlnbcrWafFTtLC4+nGXQoq2jKeWUrNJmVQlOwHOad3LyAQbotPD12vlb9wZla/nNw==", "point"=>{"service_id"=>"254", "case_id"=>"152", "status"=>"pending", "source"=>"asdf"}, "has_case"=>"Submit Point"}
  User Load (0.9ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 6], ["LIMIT", 1]]
  Case Load (0.8ms)  SELECT  "cases".* FROM "cases" WHERE "cases"."id" = $1 LIMIT $2  [["id", 152], ["LIMIT", 1]]
   (0.7ms)  BEGIN
  Service Load (1.1ms)  SELECT  "services".* FROM "services" WHERE "services"."id" = $1 LIMIT $2  [["id", 254], ["LIMIT", 1]]
   (0.5ms)  ROLLBACK
Topic must exist
Analysis can't be blank
No template found for PointsController#create, rendering head :no_content
Completed 204 No Content in 365ms (ActiveRecord: 9.7ms)
```

I'll dig into the code to see what we can do about this. If some points have a case, and others don't, maybe we should allow nil topic and nil analysis when a case is used.

**Comment by piks3l** [comment]
> maybe we should allow nil topic and nil analysis when a case is used

Or maybe preset topic and analysis ? So we don't have empty points.

**Comment by michielbdejong** [comment]
yes, the code is trying to copy the topic_id and the analysis string from the case. maybe it's missing from there, and all we need is to clean up that table.

**Comment by michielbdejong** [comment]
When following the export instructions, the local database doesn't have the case topics filled in. I needed to run `rails db` and manually fix `UPDATE "cases" SET "topic_id"=31 WHERE (id = '152');` to get it to work.

**Comment by michielbdejong** [comment]
If you look at the last two files in the diff, you see it removes and re-adds the case's topic_id: https://github.com/tosdr/phoenix/pull/263/files#diff-61ad49fa0fb9518ae802c8961144fc8e

**Comment by michielbdejong** [comment]
Merged in #369 \o/

**Pull request closed without merging**
